name: Pipeline CI - Calculadora

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  lint:
    name: 1 - Análise de Código
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: python -m pip install -r requirements.txt

      - name: Executar Linter
        run: python -m ruff check .


  testes:
    name: 2 - Testes Unitários
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: python -m pip install -r requirements.txt

      - name: Executar testes
        run: python -m pytest


  cobertura:
    name: 3 - Cobertura de Código
    needs: testes
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: python -m pip install -r requirements.txt

      - name: Verificar cobertura
        run: python -m pytest --cov=src --cov-report=term-missing --cov-fail-under=80


  seguranca:
    name: 4 - Análise de Segurança
    needs: cobertura
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: python -m pip install -r requirements.txt

      - name: Análise de segurança
        run: python -m bandit -r src